const fs=require("node:fs");
const assert=require("node:assert/strict");
const pkg=JSON.parse(fs.readFileSync("package.json","utf8"));
const src=fs.readFileSync("src/index.js","utf8");
assert.equal(pkg.name,"wxbch-public-pool");
assert.match(src,/getblocktemplate/);
assert.match(src,/submitblock/);
assert.match(src,/mining\.notify/);
assert.match(src,/mining\.submit/);
assert.match(src,/version-rolling/);
assert.match(src,/cashAddressToLockingBytecode/);
assert.match(src,/hashblock/);
console.log("WxBCH Public Pool unit smoke tests: PASS");
