const net=require('net'),http=require('http'),crypto=require('crypto');
const C={sh:process.env.STRATUM_HOST||'0.0.0.0',sp:+(process.env.STRATUM_PORT||3334),wh:process.env.WEB_HOST||'0.0.0.0',wp:+(process.env.WEB_PORT||8080),rpc:process.env.BCH_RPC_URL||'http://127.0.0.1:8332/',u:process.env.BCH_RPC_USER||'',p:process.env.BCH_RPC_PASSWORD||'',pay:process.env.BCH_PAYOUT_ADDRESS||'',diff:+(process.env.START_DIFFICULTY||1000),vmin:+(process.env.VARDIFF_MIN||1),vmax:+(process.env.VARDIFF_MAX||65536),msg:process.env.COINBASE_MESSAGE||'BCH Solo Pool'};
const D1=0x00000000ffff00000000000000000000000000000000000000000000000000n,cs=new Set(),ws=new Map();let J=null,N=0,S={accepted:0,rejected:0,blocks:0,height:0,started:Date.now()};
const H=b=>crypto.createHash('sha256').update(b).digest(),DH=b=>H(H(b));
function le32(n){let b=Buffer.alloc(4);b.writeUInt32LE(n>>>0);return b}function le64(n){let b=Buffer.alloc(8),x=BigInt(n);for(let i=0;i<8;i++){b[i]=Number(x&255n);x>>=8n}return b}
function vi(n){let x=BigInt(n);if(x<253n)return Buffer.from([Number(x)]);if(x<=65535n){let b=Buffer.alloc(3);b[0]=253;b.writeUInt16LE(Number(x),1);return b}if(x<=4294967295n){let b=Buffer.alloc(5);b[0]=254;b.writeUInt32LE(Number(x),1);return b}return Buffer.concat([Buffer.from([255]),le64(x)])}
const A='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz',CA='qpzry9x8gf2tvdw0s3jn54khce6mua7l';
function b58(s){let n=0n;for(const c of s){let i=A.indexOf(c);if(i<0)throw Error('bad base58');n=n*58n+BigInt(i)}let h=n.toString(16);if(h.length%2)h='0'+h;let b=Buffer.from(h,'hex'),z=0;for(const c of s){if(c==='1')z++;else break}return Buffer.concat([Buffer.alloc(z),b])}
function pm(v){const g=[0x98f2bc8e61n,0x79b76d99e2n,0xf33e5fb3c4n,0xae2eabe2a8n,0x1e4f43e470n];let c=1n;for(const d of v){let t=c>>35n;c=((c&0x07ffffffffn)<<5n)^BigInt(d);for(let i=0;i<5;i++)if((t>>BigInt(i))&1n)c^=g[i]}return c}
function bits(a,f,t,pad){let acc=0,b=0,o=[],m=(1<<t)-1;for(const x of a){if((x>>f)!==0)throw Error('bad bits');acc=(acc<<f)|x;b+=f;while(b>=t){b-=t;o.push((acc>>b)&m)}}if(pad&&b)o.push((acc<<(t-b))&m);if(!pad&&(b>=f||((acc<<(t-b))&m)))throw Error('bad padding');return o}
function script(a){if(a.toLowerCase().startsWith('bitcoincash:')){let s=a.toLowerCase().slice(11),v=[...s].map(c=>{let i=CA.indexOf(c);if(i<0)throw Error('bad CashAddr');return i}),pre=[...('bitcoincash')].map(c=>c.charCodeAt(0)&31);if(pm(pre.concat([0],v))!==1n)throw Error('bad CashAddr checksum');let p=bits(v.slice(0,-8),5,8,false),ver=p[0],type=ver>>3,size=[20,24,28,32,40,48,56,64][ver&7];if(type>1||p.length!==size+1)throw Error('unsupported CashAddr');let h=Buffer.from(p.slice(1));return type===0?Buffer.concat([Buffer.from('76a914','hex'),h,Buffer.from('88ac','hex')]):Buffer.concat([Buffer.from('a914','hex'),h,Buffer.from('87','hex')])}let r=b58(a);if(r.length!==25||!DH(r.subarray(0,21)).subarray(0,4).equals(r.subarray(21)))throw Error('bad legacy address');if(r[0]===0)return Buffer.concat([Buffer.from('76a914','hex'),r.subarray(1,21),Buffer.from('88ac','hex')]);if(r[0]===5)return Buffer.concat([Buffer.from('a914','hex'),r.subarray(1,21),Buffer.from('87','hex')]);throw Error('wrong BCH legacy network')}
function hs(h){let a=[];do{a.push(h&255);h>>>=8}while(h);return Buffer.concat([Buffer.from([a.length]),Buffer.from(a)])}
function rpc(m,p=[]){return new Promise((ok,no)=>{let u=new URL(C.rpc),a=C.u?Buffer.from(C.u+':'+C.p).toString('base64'):null,r=http.request({hostname:u.hostname,port:u.port||80,path:u.pathname||'/',method:'POST',headers:{'content-type':'application/json',...(a?{authorization:'Basic '+a}:{})}},x=>{let s='';x.on('data',d=>s+=d);x.on('end',()=>{try{let j=JSON.parse(s);j.error?no(Error(j.error.message)):ok(j.result)}catch(e){no(e)}})});r.on('error',no);r.end(JSON.stringify({jsonrpc:'1.0',id:Date.now(),method:m,params:p}))})}
function parts(t,ex){let s=Buffer.concat([hs(t.height),Buffer.from(C.msg),Buffer.from(ex,'hex')]),o=script(C.pay);if(s.length+8>100)throw Error('coinbase script too long');return [Buffer.concat([Buffer.from('01000000','hex'),vi(1),Buffer.alloc(32),Buffer.from('ffffffff','hex'),vi(s.length+8),s.subarray(0,s.length-4)]).toString('hex'),Buffer.concat([vi(1),le64(BigInt(t.coinbasevalue)),vi(o.length),o,Buffer.alloc(4)]).toString('hex')]}
function coin(j,e){return Buffer.concat([Buffer.from(j.c1,'hex'),Buffer.from(e,'hex'),Buffer.from(j.c2,'hex')])}
function root(c,j){let h=DH(c);for(const x of j.tx)h=DH(Buffer.concat([h,Buffer.from(x.txid||x.hash,'hex')]));return h}
function header(j,c,t,n){return Buffer.concat([le32(j.version),Buffer.from(j.prev,'hex').reverse(),root(c,j),le32(t),Buffer.from(j.bits,'hex').reverse(),le32(n)])}
function send(c,o){c.write(JSON.stringify(o)+'\n')}
function notify(c,clean){if(!J)return;send(c,{id:null,method:'mining.set_difficulty',params:[c.diff]});send(c,{id:null,method:'mining.notify',params:[J.id,J.prev,J.c1,J.c2,J.tx.map(x=>x.txid||x.hash),[],le32(J.version).toString('hex'),J.bits,J.curtime,clean]})}
async function newJob(clean=true){let t=await rpc('getblocktemplate',[{rules:[]}]);if(!C.pay)throw Error('BCH_PAYOUT_ADDRESS is required');let p=parts(t,crypto.randomBytes(4).toString('hex'));J={id:(++N).toString(16),prev:t.previousblockhash,version:t.version,bits:t.bits,curtime:t.curtime,height:t.height,target:BigInt('0x'+t.target),coinbasevalue:t.coinbasevalue,tx:t.transactions||[],c1:p[0],c2:p[1]};S.height=t.height;for(const c of cs)if(c.auth)notify(c,clean)}
async function submit(c,p){if(!J||p[0]!==J.id)return false;let cb=coin(J,p[2]),h=header(J,cb,parseInt(p[3],16)>>>0,parseInt(p[4],16)>>>0),v=BigInt('0x'+DH(h).reverse().toString('hex')),target=D1/BigInt(Math.max(1,Math.floor(c.diff)));if(v>target)return false;S.accepted++;let w=ws.get(c.worker)||{worker:c.worker,accepted:0,rejected:0,diff:c.diff};w.accepted++;w.diff=c.diff;ws.set(c.worker,w);if(v<=J.target){let raw=Buffer.concat([h,vi(1+J.tx.length),cb,...J.tx.map(x=>Buffer.from(x.data,'hex'))]).toString('hex');try{let r=await rpc('submitblock',[raw]);if(r===null){S.blocks++;console.log('BCH BLOCK ACCEPTED')}}catch(e){console.error('submitblock:',e.message)}}return true}
function line(c,s){let m;try{m=JSON.parse(s)}catch{return}let{id,method,params=[]}=m;if(method==='mining.subscribe'){send(c,{id,result:[[['mining.set_difficulty','1']],c.ex],error:null});return}if(method==='mining.authorize'){let w=String(params[0]||''),a=w.split('.')[0];try{script(a);c.worker=w;c.auth=true;c.diff=C.diff;send(c,{id,result:true,error:null});notify(c,true)}catch(e){send(c,{id,result:false,error:[20,e.message,null]})}return}if(method==='mining.configure'){send(c,{id,result:{'version-rolling':true,'version-rolling.mask':'1fffe000'},error:null});return}if(method==='mining.extranonce.subscribe'){send(c,{id,result:true,error:null});return}if(method==='mining.suggest_difficulty'){let d=+params[0];if(Number.isFinite(d))c.diff=Math.max(C.vmin,Math.min(C.vmax,d));send(c,{id,result:true,error:null});return}if(method==='mining.submit'){if(!c.auth)return send(c,{id,result:null,error:[24,'unauthorized',null]});submit(c,params).then(ok=>{if(!ok){S.rejected++;let w=ws.get(c.worker)||{worker:c.worker,accepted:0,rejected:0,diff:c.diff};w.rejected++;ws.set(c.worker,w)}send(c,{id,result:ok,error:ok?null:[23,'low difficulty share',null]})});return}if(id!==undefined)send(c,{id,result:null,error:[-32601,'method not found',null])}}
const st=net.createServer(c=>{c.setEncoding('utf8');c.buf='';c.auth=false;c.ex=crypto.randomBytes(4).toString('hex');c.diff=C.diff;cs.add(c);c.on('data',d=>{c.buf+=d;let i;while((i=c.buf.indexOf('\n'))>=0){let s=c.buf.slice(0,i);c.buf=c.buf.slice(i+1);line(c,s)}});c.on('close',()=>cs.delete(c));c.on('error',()=>cs.delete(c))});
const web=http.createServer((q,r)=>{if(q.url==='/health'){r.writeHead(200,{'content-type':'application/json'});return r.end(JSON.stringify({ok:true,height:S.height,clients:cs.size}))}if(q.url==='/api/status'){r.writeHead(200,{'content-type':'application/json'});return r.end(JSON.stringify({pool:'BCH Solo Pool',coin:'BCH',height:S.height,clients:cs.size,accepted:S.accepted,rejected:S.rejected,blocks:S.blocks,uptime:Math.floor((Date.now()-S.started)/1000),workers:[...ws.values()]}))}r.writeHead(200,{'content-type':'text/html'});r.end('<!doctype html><meta name=viewport content="width=device-width"><title>BCH Solo Pool</title><style>body{font:16px system-ui;background:#0b0d10;color:#eee;max-width:1100px;margin:40px auto;padding:20px}.g{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.c{background:#151922;border:1px solid #292e3a;border-radius:12px;padding:18px}table{width:100%;margin-top:25px}td,th{padding:9px;text-align:left;border-bottom:1px solid #292e3a}</style><h1>BCH Solo Pool</h1><div class=g id=s></div><table><thead><tr><th>Worker</th><th>Accepted</th><th>Rejected</th><th>Difficulty</th></tr></thead><tbody id=w></tbody></table><script>async function x(){let a=await fetch("/api/status").then(r=>r.json());s.innerHTML=[["Height",a.height],["Miners",a.clients],["Accepted",a.accepted],["Rejected",a.rejected]].map(x=>"<div class=c>"+x[0]+"<h2>"+x[1]+"</h2></div>").join("");w.innerHTML=a.workers.map(x=>"<tr><td>"+x.worker+"</td><td>"+x.accepted+"</td><td>"+x.rejected+"</td><td>"+x.diff+"</td></tr>").join("")}x();setInterval(x,3000)</script>')});
st.listen(C.sp,C.sh,()=>console.log('BCH Stratum '+C.sh+':'+C.sp));web.listen(C.wp,C.wh,()=>console.log('BCH Web '+C.wh+':'+C.wp));
(async()=>{for(;;){try{await newJob(true)}catch(e){console.error('template:',e.message)}await new Promise(r=>setTimeout(r,5000))}})();